### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by chessai** [ollef/parsix#1]
Would you be averse to releasing 'parsix' to Hackage? I think it would be pretty useful.

**Comment by ollef** [comment]
I intend to do so eventually, after I've tried out some new things for Sixten's LSP integration and when I feel the API has stabilised a bit. If you still want to use it in the meantime, e.g. Stack has support for git dependencies.

**Comment by chessai** [comment]
I'm already using it with nix - I just thought that a hackage release would be a good idea and kept meaning to open up an issue (didn't know if you had considered it yet). Thanks!

**Comment by danr** [comment]
Hej Olle! We're using parsix for some serious business, ha ha ha. Right now we are using it with nix and while it works fine it would be nice to have a hackage release to point to :) 
Cheers!

**Comment by ollef** [comment]
Hej!

Since there seems to be so much serious business depending on this library, I've now made a release: https://hackage.haskell.org/package/parsix

PS I hope it's not related to chains of blocks!
